### ISSUE TITLE
讨论下UC的超级登录

### ISSUE THREAD

**Issue by captainblue2013** [captainblue2013/fyscu_uc_v3#3]
一开始，计划超级登录是一个redirect，跳转到某页面，再跳转回来，
但是后来还想支持接口api，让应用不用额外做callback页面，直接得到 uid 和 accessToken，
晚上争取实现出来。

2015-12－30

**Comment by dsgygb** [comment]
哦

**Comment by captainblue2013** [comment]
遇到一个问题，想清楚之前超级登录估计都不会上，
就是，目前只对帐号做签名就可以实现登录，md5('some_string'+account),
岂不是只要app方知道用户帐号即可随便读取userinfo？这样对用户来说是不是太没隐私了？
